-- MySQL Script generated by MySQL Workbench
-- Wed Sep 20 14:54:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank` DEFAULT CHARACTER SET utf8 ;
USE `bank` ;

-- -----------------------------------------------------
-- Table `bank`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `registerationDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `openingDate` DATETIME NULL DEFAULT current_timestamp,
  `balance` DECIMAL NULL DEFAULT 0.00,
  `Customers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Accounts_Customers_idx` (`Customers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Accounts_Customers`
    FOREIGN KEY (`Customers_id`)
    REFERENCES `bank`.`Customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`Transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `amount` DECIMAL NULL,
  `Accounts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Transactions_Accounts1_idx` (`Accounts_id` ASC) VISIBLE,
  CONSTRAINT `fk_Transactions_Accounts1`
    FOREIGN KEY (`Accounts_id`)
    REFERENCES `bank`.`Accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
